apiVersion: v1
kind: Service
metadata:
  name: visualization-settings-db-service
  labels:
    app: visualization-settings-db
spec:
  #  ports:
  #    - name: http
  #      port: 5432
  #      targetPort: 5432
  #  type: LoadBalancer
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: visualization-settings-db
