apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv-volume
  labels:
    app: kafka
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/hipr/kafka-data