apiVersion: v1
kind: Service
metadata:
  name: kafka-ui-service
  labels:
    app: kafka-ui
spec:
  selector:
    app: kafka-ui
  ports:
    - port: 8080
  #    - name: http
  #      port: 8080
  #      targetPort: 8080
  type: NodePort
