---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  labels:
    app: kafka
spec:
  ports:
    - name: kafka-port
      port: 9092
      protocol: TCP
  #  ports:
  #    - port: 9092
  #      name: kafka-port
  #      targetPort: 9092
  #      protocol: TCP
  selector:
    app: kafka
  type: ClusterIP
#  externalIPs:
#    - 192.168.127.20
