apiVersion: v1
kind: Service
metadata:
  name: command-queue-srv-service
spec:
  selector:
    app: command-queue-srv
  #  type: NodePort
  #  ports:
  #    - port: 9075
  ports:
    - name: ws
      port: 9075
      targetPort: 9075
  type: LoadBalancer
  externalIPs:
    - 192.168.1.178
