# https://github.com/oauth2-proxy/oauth2-proxy/blob/7c3efe4f42bc37ccab613fe5002c172e147e3195/docs/2_auth.md#keycloak-auth-provider
extraArgs:
  provider: keycloak
  set-xauthrequest: true
  provider-display-name: HIPR Login
  client-id: dcs-ui # Change XXX to your client_id
  client-secret: vgPWUJizANPLLfFPJrXVT8XY2UilS0sy # Change XXX to your client_secret
  login-url: "https://keycloak:8080/auth/realms/dcs/protocol/openid-connect/auth" # Change REALM_NAME to your realm
  redeem-url: "https://keycloak:8080/auth/realms/dcs/protocol/openid-connect/token" # Change REALM_NAME to your realm
  validate-url: "https://keycloak:8080/auth/realms/dcs/protocol/openid-connect/userinfo" # Change REALM_NAME to your realm
  keycloak-group: dcs # Change XXX by your group that shall have access to it

replicaCount: 2
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            app: oauth2-proxy
        topologyKey: "kubernetes.io/hostname"
resources:
  limits:
    cpu: 200m
    memory: 100Mi
  requests:
    cpu: 100m
    memory: 25Mi
