apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: data-server-deployment
spec:
#  replicas: 1
  selector:
    matchLabels:
      app: data-server
  template:
    metadata:
      labels:
        app: data-server
    spec:
      containers:
        - name: data-server
          image: skylis/dcs_data_server2:0.9.21
          imagePullPolicy: Always
          ports:
            - containerPort: 9029
              protocol: UDP
          env:
            - name: KAFKA_HOST
              value: kafka-service:9092
            - name: INFLUXDB_HOST
              value: influxdb-service
            - name: INFLUXDB_PORT
              value: "8086"
            - name: INFLUXDB_METRICS_DB_NAME
              value: dcs_metrics_db
            - name: KAFKA_SETTINGS_UPDATE_TOPIC
              value: Functional.device.settings.changes
            - name: KAFKA_LOG_TOPIC
              value: dcs.dataserver.log
            - name: SETTINGS_SERVER_HOST
              value: dcs-nodes-service
            - name: SETTINGS_SERVER_PORT
              value: "8000"
            - name: REDIS_HOST
              value: redis-service
            - name: REDIS_PORT
              value: "6379"
            - name: COMMON_KEY_MONITOR
              value: values.updated.timestamp
            - name: COMMON_KEY_PROPAGATE
              value: values.last
