apiVersion: v1
kind: Service
metadata:
  name: data-server-service
spec:
  selector:
    app: data-server
#  type: LoadBalancer
#  externalIPs:
#    - 192.168.127.20
  ports:
    - protocol: UDP
      port: 9029
      targetPort: 9029
