apiVersion: v1
kind: Service
metadata:
  name: node-db-service
  labels:
    app: node-db
spec:
  #  ports:
  #    - name: http
  #      port: 5432
  #      targetPort: 5432
  #  type: LoadBalancer
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: node-db
