apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-postgres
spec:
  selector:
    matchLabels:
      app: keycloak
  replicas: 1
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: postgres
          image: postgres:14.5-alpine
          env:
            - name: POSTGRES_DB
              value: bitnami_keycloak
            - name: POSTGRES_USER
              value: bn_keycloak
            - name: POSTGRES_PASSWORD
              value: "#3]O?4RGj)DE7Z!9SA5"
            - name: POSTGRES_LOGGING_COLLECTOR
              value: "off"
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: keycloak-postgres-volume
              mountPath: /var/lib/postgresql/data
              subPath: postgres
      volumes:
        - name: keycloak-postgres-volume
          persistentVolumeClaim:
            claimName: keycloak-postgres-pvc

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: bitnamilegacy/keycloak:24.0.5
          env:
            - name: KEYCLOAK_PROXY
              value: "edge"
#            - name: KEYCLOAK_HTTP_ENABLED
#              value: "true"
            - name: KEYCLOAK_HTTP_PORT
              value: "18080"
            - name: KEYCLOAK_HTTP_RELATIVE_PATH
              value: "/auth"
            - name: KEYCLOAK_DATABASE_HOST
              value: "keycloak-postgres"
            - name: KEYCLOAK_DATABASE_PASSWORD
              value: "#3]O?4RGj)DE7Z!9SA5"
            - name: KEYCLOAK_ADMIN_USER
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "Y5q-MUV-6zt-dDe"
            - name: JAVA_OPTS
              value: "-XX:+UseZGC -XX:MaxRAMPercentage=75.0"
            - name: KEYCLOAK_PRODUCTION
              value: "true"
            - name: KEYCLOAK_HEAP_SIZE
              value: "1G"
          ports:
            - containerPort: 18080
              name: http
          volumeMounts:
            - name: tls-secret
              mountPath: /opt/bitnami/keycloak/certs
              readOnly: true
          readinessProbe:
            httpGet:
              path: '/auth/realms/master'
              port: 18080
            initialDelaySeconds: 90
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: '/auth/realms/master'
              port: 18080
            initialDelaySeconds: 90
            periodSeconds: 15
            timeoutSeconds: 5
      volumes:
        - name: tls-secret
          secret:
            secretName: keycloak-tls
