apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: keycloak-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: keycloak.dcs
      http:
        paths:
          - path: /auth(/|$)(.*)
            backend:
              serviceName: keycloak
              servicePort: 8080
