apiVersion: v1
kind: Service
metadata:
  name: keycloak-postgres
  labels:
    app: keycloak
spec:
  ports:
    - port: 5432
  selector:
    app: keycloak
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
  selector:
    app: keycloak
#  externalIPs:
#    - 192.168.1.178
