apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-postgres-pv
  labels:
    type: local
    app: keycloak-postgres
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/cephfs/keycloak-postgres"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-postgres-pvc
  labels:
    app: keycloak-postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
