apiVersion: apps/v1
kind: Deployment
metadata:
  name: command-server-deployment
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: command-server
  template:
    metadata:
      labels:
        app: command-server
    spec:
#      hostNetwork: true
      containers:
        - name: command-server
          image: skylis/dcs_command_server:0.8.1
          imagePullPolicy: Always
          ports:
            - containerPort: 9020
              protocol: UDP
            - containerPort: 9030
              protocol: UDP
          env:
            - name: KAFKA_HOST
              value: "192.168.127.20:9092"
            - name: REDIS_HOST
              value: redis-service
            - name: REDIS_PORT
              value: "6379"
            - name: STATUS_KEY_MONITOR
              value: status.updated.timestamp
            - name: STATUS_KEY_PROPAGATE
              value: status.last
            - name: COMMANDS_TOPIC
              value: dcs.device.commands
            - name: BROADCAST_PORT
              value: "9030"
            - name: BROADCAST_MASK
              value: "192.168.127.255"
            - name: COMMAND_RESPONSE_PORT
              value: "9031"
            - name: COMMAND_RESPONSE_ADDRESS
              value: "0.0.0.0"
            - name: BROADCAST_HOST_ADDRESS
              value: "0.0.0.0"
