apiVersion: apps/v1
kind: Deployment
metadata:
  name: device-response-receiver-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: device-response-receiver
  template:
    metadata:
      labels:
        app: device-response-receiver
    spec:
#      hostNetwork: true
      containers:
        - name: device-response-receiver
          image: skylis/dcs-device-response-receiver:1.0.2
          imagePullPolicy: Always
          ports:
            - containerPort: 9031
              protocol: UDP
          env:
            - name: KAFKA_HOST
              value: "kafka-service:9092"
            - name: REDIS_HOST
              value: redis-service
            - name: REDIS_PORT
              value: "6379"
            - name: STATUS_KEY_MONITOR
              value: status.updated.timestamp
            - name: STATUS_KEY_PROPAGATE
              value: status.last
            - name: COMMAND_RESPONSE_PORT
              value: "9031"
            - name: COMMAND_RESPONSE_ADDRESS
              value: "0.0.0.0"
