---
# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oauth-proxy
  name: oauth-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "oauth-proxy"
  template:
    metadata:
      labels:
        app: oauth-proxy
    spec:
      containers:
        - name: oauth-proxy
          image: "quay.io/oauth2-proxy/oauth2-proxy:v7.4.0"
          env:
            # OIDC Config
            - name: "OAUTH2_PROXY_PROVIDER"
              value: "oidc"
            - name: "OAUTH2_PROXY_OIDC_ISSUER_URL"
              value: "http://keycloak:8080"
            - name: "OAUTH2_PROXY_CLIENT_ID"
              value: "dcs-ui"
            - name: "OAUTH2_PROXY_CLIENT_SECRET"
              value: "vgPWUJizANPLLfFPJrXVT8XY2UilS0sy"

            # Cookie Config
            - name: "OAUTH2_PROXY_COOKIE_SECRET"
              value: "secret"
            - name: "OAUTH2_PROXY_COOKIE_DOMAINS"
              value: "dcs"
            # Proxy config
            - name: "OAUTH2_PROXY_EMAIL_DOMAINS"
              value: "dcs"
            - name: "OAUTH2_PROXY_WHITELIST_DOMAINS"
              value: "dcs"
            - name: "OAUTH2_PROXY_HTTP_ADDRESS"
              value: "0.0.0.0:4180"
            - name: "OAUTH2_PROXY_SET_XAUTHREQUEST"
              value: "true"
            - name: "OAUTH2_PROXY_UPSTREAMS"
              value: "file:///dev/null"
---
# ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: oauth-proxy
  name: oauth-proxy
spec:
  rules:
    - host: dcs
      http:
        paths:
          - path: /oauth2
            pathType: Prefix
            backend:
              service:
                name: oauth-proxy
                port:
                  number: 4180
---
