version: '2.0'
services:
  registry:
    image: registry:2.7
    ports:
      - "5000:5000"
    environment:
      #REGISTRY_HTTP_HEADERS_Access-Control-Allow-Origin: "['*']"
      #REGISTRY_HTTP_TLS_CERTIFICATE: /certs/kov-slave.crt
      #REGISTRY_HTTP_TLS_KEY: /certs/kov-slave.key
      REGISTRY_HTTP_SECRET: secret
      #REGISTRY_AUTH: htpasswd
      #REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      #REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    volumes:
      - ./data:/var/lib/registry
      - ./registry-config/simple.yml:/etc/docker/registry/config.yml
    networks:
      - registry-ui-net

  registry-ui:
    image: joxit/docker-registry-ui:latest
    ports:
      - "5001:80"
    environment:
      - REGISTRY_TITLE=My Private Docker Registry
      - NGINX_PROXY_PASS_URL=http://registry:5000
      - SINGLE_REGISTRY=true
    depends_on:
      - registry
    networks:
      - registry-ui-net

networks:
  registry-ui-net:
