apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - env:
        - name: REGISTRY_HTTP_SECRET
          value: secret
        - name: REGISTRY_HTTP_TLS_CERTIFICATE
          value: /certs/tls.crt
        - name: REGISTRY_HTTP_TLS_KEY
          value: /certs/tls.key
        image: registry:2.7
        name: registry
        ports:
        - containerPort: 5000
        volumeMounts:
          - mountPath: /var/lib/registry
            name: registry-data
          - mountPath: /etc/docker/registry/config.yml
            name: config-volume
            subPath: config.yml
          - mountPath: /certs
            name: tls-certs
      volumes:
        - name: registry-data
          persistentVolumeClaim:
            claimName: registry-pv-claim
        - configMap:
            name: registry-config
          name: config-volume
        - name: tls-certs
          secret:
            secretName: registry-tls
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-tls
type: kubernetes.io/tls
data:
  tls.crt: |+
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURHVENDQWdHZ0F3SUJBZ0lVSUxOZWZzd1FH
    N0lldE1PaC92Ry9ETnZ6U2pjd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0hERWFNQmdHQTFVRUF3d1Jj
    bVZuYVhOMGNua3VhR2x3Y2k1ck9ITXdIaGNOTWpReE1USTNNVFl5TXpFeQpXaGNOTWpVeE1USTNN
    VFl5TXpFeVdqQWNNUm93R0FZRFZRUUREQkZ5WldkcGMzUnllUzVvYVhCeUxtczRjekNDCkFTSXdE
    UVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTngxMTF6L2NOa0NQTC9zNnpIRS85
    dzEKa1BBZ1FNcVlhNmkrMW1YTzllbkRUN21oakxzb0lLc0xYVVgxSTlWUU53NFZRNkhFRC9BMTN6
    T1hkb2lvUkp3VQpFOVZJQkpTWStRN2liTVhEN1BXUTdhOVNxODdjZnZ2b0pOdjVCTmFMbUZ2UzZy
    TVkvemhCUkljcWYzbzRHUTRaClN6MWwwN1MyV0ZPMXFOYTJudCthdnd2b1N6NGZEa3FuUEcxaXBJ
    Y2t4TFJZUlQzdklwcTZFVzdHQVYyaFZ2RmwKaVJ4Mm1VQjJYV3pPLzlTdmt4OGRBV2ZkT3VPU29i
    cjkzOEtYZytsRis1Z0h1emtPWEh0bHRVK3JYVmQzbGJuSApyYW95dk03NW1uaDNhS3l5OCt0Tm9X
    WEE0UHlPR2pIaHBTUndsVlFnN0t5K0ZKQVJzNDI4TzR5V3d3dWV2ekVDCkF3RUFBYU5UTUZFd0hR
    WURWUjBPQkJZRUZOWmY4UVpQY3U2Z2UvNXNHeDlhUU16VlVaaDVNQjhHQTFVZEl3UVkKTUJhQUZO
    WmY4UVpQY3U2Z2UvNXNHeDlhUU16VlVaaDVNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdEUVlKS29a
    SQpodmNOQVFFTEJRQURnZ0VCQUd1d0RvQmFLTHBYQjZ2dFJNSEFuUUpKZXJJeWIrcEhGUUdxUmto
    aTJURFE3Uy83CjdITVFSWHp3NUVzeVlLOE9yOGUzUkU4OUxaSyswZ2ZxbFlJK3kwODFlaWp0MGZz
    b3RTNDl1TlNIVCs2Vk5wdDcKb2tlbndLZUROdE1mTkpFd1dsa3k4MnBualVtMUFEK0pwZll2dkdG
    R1R5bGErdE5VMDJ2STRYMDVxcWI0WG1qWQo2V2Q1WUM4WHRHVGxHaXlueWpBUWtBSVNMWExsS2Yy
    Z1RsRHlqTUtVMmRYam1HNEhEZzFpUC82VEJ3dTNwQlRPCnVoL1FNejkybG00SUtXMThtcTQ0U093
    Uy9jd2VuT0dGRU80M3hybUxiVnhuRlpkbW9wQXZqQUxtdzNiMFR4S2UKdVRkR1FWK2prUUMwOXN6
    aW9mZGxCL01HUm1sa3lLdTZ3REpyRXFFPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: |+
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2QUlCQURBTkJna3Foa2lHOXcwQkFRRUZB
    QVNDQktZd2dnU2lBZ0VBQW9JQkFRRGNkZGRjLzNEWkFqeS8KN09zeHhQL2NOWkR3SUVES21HdW92
    dFpsenZYcHcwKzVvWXk3S0NDckMxMUY5U1BWVURjT0ZVT2h4QS93TmQ4egpsM2FJcUVTY0ZCUFZT
    QVNVbVBrTzRtekZ3K3oxa08ydlVxdk8zSDc3NkNUYitRVFdpNWhiMHVxekdQODRRVVNICktuOTZP
    QmtPR1VzOVpkTzB0bGhUdGFqV3RwN2ZtcjhMNkVzK0h3NUtwenh0WXFTSEpNUzBXRVU5N3lLYXVo
    RnUKeGdGZG9WYnhaWWtjZHBsQWRsMXN6di9VcjVNZkhRRm4zVHJqa3FHNi9kL0NsNFBwUmZ1WUI3
    czVEbHg3WmJWUApxMTFYZDVXNXg2MnFNcnpPK1pwNGQyaXNzdlByVGFGbHdPRDhqaG94NGFVa2NK
    VlVJT3lzdmhTUUViT052RHVNCmxzTUxucjh4QWdNQkFBRUNnZ0VBREdWZjM2M0pSWnAzbWY4VFZu
    QVNSdXFJSk1oYmZFakh2T3hHRitGa09HbXcKQU9zUmc3Q0U3YmtzM0hNbE9haFNBQ3UzNnMrZ2Fj
    eE5xWlA1cVVOMDRDWE0yN0E1K2JVRVJBNzlPTDJFaEdaSwp4eEhwOFM2NndTVlRkVDd5UTdJRHRo
    NE03bGNZZXF4STB5VFRtQ2F4V2ZhWUlYS3BUYjczQm5YdmNXdEJVYWRDCkhzNkx1Q0t5Y0NkTi9G
    cGFLQlRlc3dGN09ZWjNMNDh2OU1TVExwOGtXdCtycW4ybUhMQWtOOUZEMWs5MEdKdTQKRjJTMGZF
    Z2ZMNXgrSWJuZ2xWOEQ2UzRXZ1NxR3pzSDFLdVQ4bVZ2NHFabFYvcWRGS3QycnRESzJSYW44SXlO
    Qgp4dzhwTndKRWR1a0ZmeUJTOTg1SGZuanR4Z0NiY0xGWk1YNmI5cW1hQVFLQmdRRG5EWSs1VWRS
    Rk1HUjdxTFJWCnR6UExNRHdheE1YWHNtbk5XRnQ0Um15NzFVcmYza29kY1o1THNpS2c3YTU1RFp3
    MFAyeW4vN2Jtd252U3ZuRDIKcklqYVBndU5aL01YTThHMVZWTXFMZXNwY3NoWWNsY0pxMXhlS0lD
    a1N3SmxJYURoaGRhMWdUdGdUTWFRVEloSgpIYnZKbmI1QWJWb0VGWDVXSnZIQVdlQUJJUUtCZ1FE
    MFEzNGQvNU43VGo0b2d4T3pLdUIwc2t1cS9tMklkUGRPCnVEOE0zUGRuV2xrbHVTOUtRSHNONlVF
    emd6bFlUMWhTSGdpRDBObkFyNVlCdnlwWjRZMHRBbEFmSkExeW4rS0gKWXdhKzZkK2x3bko1YWNv
    UkRlR09LSG5CcFdmbnM3SFRwdUlwWXNRMVp0Znh3QmRrY3VNUkZUanFwaUZBRmsxMwpLR0tRaU8w
    c0VRS0JnQmkwK29sMmxweFBjRzlJdXYvdmR6cGpEZ3BPd0Zrd1d0LzZjczJKdWxiYm1BWVlYeFNH
    CjhjWm1aZzJQWFBqVTI3ODZpUVB0OUVENHl3VGVHSFpJUE5vWmlHSzJtdWdBUU5hREtVRjVaNHdu
    R2dWYk5MTnoKLzR5U0NDK0pWZGc2b0ZsOVZsaFNXV2NTenFqZmhqTkxXcWxVbE9PT3pmRmgyd0Ni
    YVg2SUhjd0JBb0dBQTRTMQpYRmxDRnBTWjhKdHl2VEh3NmIxbnVaN1FsUmFhT1ZnT0VIRmVYdTYr
    T2Z6ZzRZRHNSTmNIU1dhcWZNc255b2NFCk9HSFp3UnpHWEdBVWpCYmpvYkpXMVJ2LzFaYlgvSHRB
    clo5UXlXSnpvNndTYlF4MkkwWVIrdWdYQnc5ZmtGem4KQlJHWEllM0pUb0lsMUJ5VGlMdDFobXUr
    THQ0alg0UUZaMitSZXdFQ2dZQVRHZis3ejQ3YjNNV0dLN1BPZ1ZFQgpGOUJvWEZVWXJBZXUvT1B5
    Y1ZoVEducmFFeCtnMkh4bngrMkhDK2w0ejRHYVNPUDdHalpyRzkwREdacFo3dkRUCmp3cWVyd1Fv
    bW9zU3lEWUloWUozcThQbmlmV2hLUnRISlZIZlZTZWFIalZuOFE2dHJnV1NuN0FRRlE0TldQaVkK
    VUl5WWc2ak9QaW9nMmZySDNHQ1ZQZz09Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
