apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - env:
        - name: REGISTRY_HTTP_SECRET
          value: secret
        - name: REGISTRY_HTTP_TLS_CERTIFICATE
          value: /certs/tls.crt
        - name: REGISTRY_HTTP_TLS_KEY
          value: /certs/tls.key
        image: registry:2.7
        name: registry
        ports:
        - containerPort: 5000
        volumeMounts:
          - mountPath: /var/lib/registry
            name: registry-data
          - mountPath: /etc/docker/registry/config.yml
            name: config-volume
            subPath: config.yml
          - mountPath: /certs
            name: tls-certs
      volumes:
        - name: registry-data
          persistentVolumeClaim:
            claimName: registry-pv-claim
        - configMap:
            name: registry-config
          name: config-volume
        - name: tls-certs
          secret:
            secretName: registry-tls
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-tls
type: kubernetes.io/tls
data:
  tls.crt: |+
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrakNDQVRlZ0F3SUJBZ0lJVHR1VEJrRUp5ZTB3Q2dZSUtvWkl6ajBFQXdJd0l6RWhNQjhHQTFVRUF3d1kKYXpOekxXTnNhV1Z1ZEMxallVQXhOek13TlRRME56TTBNQjRYRFRJME1URXdNakV3TlRJeE5Gb1hEVEkxTVRFdwpNakV3TlRJeE5Gb3dNREVYTUJVR0ExVUVDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGVEFUQmdOVkJBTVRESE41CmMzUmxiVHBoWkcxcGJqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJCSCtFcmNpbHQ2amkyekQKV3Exc252ckhsaHUyOXRqOFdCYWVLRmRURG5IZ1ZZYXkrT1YxelRIRkJsZGhnTXNCc2huV3Y3ZW9pNlVnQjV6cQpJamR2ZkN1alNEQkdNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFmCkJnTlZIU01FR0RBV2dCUmV4SXhobW02M2tObWVWeTZwZ1MxMTh5cWJ1ekFLQmdncWhrak9QUVFEQWdOSkFEQkcKQWlFQWpLcU1oTlUwcHlHSklOZExQT2l2eTNldmVWMUFBeCtaL1hrQ0dONVdONHNDSVFEblBJMzQ3Y3NLY0pvcwpCUVcyVkZIcFlqcGdma0gyMURSZTY4dXpScmVPbFE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCZURDQ0FSMmdBd0lCQWdJQkFEQUtCZ2dxaGtqT1BRUURBakFqTVNFd0h3WURWUVFEREJock0zTXRZMnhwClpXNTBMV05oUURFM016QTFORFEzTXpRd0hoY05NalF4TVRBeU1UQTFNakUwV2hjTk16UXhNRE14TVRBMU1qRTAKV2pBak1TRXdId1lEVlFRRERCaHJNM010WTJ4cFpXNTBMV05oUURFM016QTFORFEzTXpRd1dUQVRCZ2NxaGtqTwpQUUlCQmdncWhrak9QUU1CQndOQ0FBUTFkOXB5VDd5Nyt0QU5TS1ZQa1R4K2txY1FRQjZpTUlWZnFIRW1YVExXCnpRNStXQWxZekI5eTgrYms4WTVWRmVIa2EyZ3EvRUI3WlMrS3V4cVVZbk1VbzBJd1FEQU9CZ05WSFE4QkFmOEUKQkFNQ0FxUXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVVYc1NNWVpwdXQ1RFpubGN1cVlFdApkZk1xbTdzd0NnWUlLb1pJemowRUF3SURTUUF3UmdJaEFJQWhlejc4dnpVSyt3Z0VUK1Ztc2JBWDlQVTFhSDRYClFISG43ZXhhZy9DN0FpRUE4UmM5K3o1ZTZadi9tMGlDS3pmSWt6YVlrcWxoaXlCbTJrUkJ4R3hKZjdZPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: |+
    LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUhtUkhPL3dwa0VvT01NZEFsa1BOWHNneGVKQlZSeHpzYnA1R2RRRUIzS0VvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFRWY0U3R5S1czcU9MYk1OYXJXeWUrc2VXRzdiMjJQeFlGcDRvVjFNT2NlQlZockw0NVhYTgpNY1VHVjJHQXl3R3lHZGEvdDZpTHBTQUhuT29pTjI5OEt3PT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
