apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - env:
        - name: REGISTRY_HTTP_SECRET
          value: secret
#        - name: REGISTRY_HTTP_TLS_CERTIFICATE
#          value: /certs/tls.crt
#        - name: REGISTRY_HTTP_TLS_KEY
#          value: /certs/tls.key
        image: registry:2.7
        name: registry
        ports:
        - containerPort: 5000
        volumeMounts:
          - mountPath: /var/lib/registry
            name: registry-data
          - mountPath: /etc/docker/registry/config.yml
            name: config-volume
            subPath: config.yml
#          - mountPath: /certs
#            name: tls-certs
      volumes:
        - name: registry-data
          persistentVolumeClaim:
            claimName: registry-pv-claim
        - configMap:
            name: registry-config
          name: config-volume
#        - name: tls-certs
#          secret:
#            secretName: registry-tls
---
#apiVersion: v1
#kind: Secret
#metadata:
#  name: registry-tls
#type: kubernetes.io/tls
#data:
#  tls.crt: |+
#    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURxVENDQXBHZ0F3SUJBZ0lVTmFvNXFlYWkz
#    dEVCaVRCWEs0ZGV5Ukl6Si9zd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1hqRUxNQWtHQTFVRUJoTUNV
#    bFV4RWpBUUJnTlZCQWdNQ1ZOdmJXVlRkR0YwWlRFUk1BOEdBMVVFQnd3SQpVMjl0WlVOcGRIa3hE
#    REFLQmdOVkJBb01BMFJEVXpFYU1CZ0dBMVVFQXd3UmNtVm5hWE4wY25rdWFHbHdjaTVyCk9ITXdI
#    aGNOTWpReE1USTNNVGt6TVRNeFdoY05NalV4TVRJM01Ua3pNVE14V2pCZU1Rc3dDUVlEVlFRR0V3
#    SlMKVlRFU01CQUdBMVVFQ0F3SlUyOXRaVk4wWVhSbE1SRXdEd1lEVlFRSERBaFRiMjFsUTJsMGVU
#    RU1NQW9HQTFVRQpDZ3dEUkVOVE1Sb3dHQVlEVlFRRERCRnlaV2RwYzNSeWVTNW9hWEJ5TG1zNGN6
#    Q0NBU0l3RFFZSktvWklodmNOCkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFKbjhGOHFrOWxxUzY4
#    NHZqRi9qSGcxZ1pwVXJXenJoSVE5b3VNZVEKaExBYU9uNk5YU3RVMkdYd2QyQWExZFRFNVdYc3NN
#    QkNnblp0NCs0aUtacmFVUWJIeGQwMVRhWTU1T3VORXg5RwpxTVVmRlY2andac0lmaGZPTWxpQ2p2
#    bzR2N3pmay9oOWk3Wk1RVWNYYjBveW9PbUFNL1FjOWJLN21tVGRES0drCkJINVg5UkVmWjl0S1Za
#    QW1FSFhjeEVpNTZWOSs5YmgwT2hDZ2dCcmd3cmZwMzRSQ1JncWxXN3FBa2hVWVYvdjQKd2VubDZi
#    M2R1R0RMRWw1VVFteDZob0QreWxJRU9SSVpSUkRPYmdGc1dQb1BkTFZkOFVrejltbHMvK3p0RzI3
#    ZApKbkZROGQrK2thMHFpb3N4Q1EvSFNNbXNiR1ZvTXl5TmQ4Wlk3RU10SDl1SDY1VUNBd0VBQWFO
#    Zk1GMHdQQVlEClZSMFJCRFV3TTRJUmNtVm5hWE4wY25rdWFHbHdjaTVyT0hPQ0ZISmxaMmx6ZEhK
#    NUxYVnBMbWhwY0hJdWF6aHoKZ2dob2FYQnlMbXM0Y3pBZEJnTlZIUTRFRmdRVXNlSmVGak83aDZ0
#    Vko5TUlJTGN6c2IzOW12VXdEUVlKS29aSQpodmNOQVFFTEJRQURnZ0VCQUlnd2NBTkthRzVzV2F1
#    QytRd0UzdE12cVpXYmZzS3BZL005akdyMDI0YmRPa203CkQ3cE9WdnllT2ZYN04zQzVVZDVPYlNR
#    dVlMTnBxRW9KUklyZENpbjhEUDBlSTBZdkhmKzBpakZhWXExdGRnT1QKT2JXdDVTNlI3VlZoZjBI
#    dVF4ejJVcWNrMG9wWDEyRkthcDkrSHFlclZlN29ZTHhWNWxSM0owajJjSGdDV1h0VwpBa0V3Zm50
#    Tmp5TkN4MXhxM1dhUHRyRjJDR1JKYXVaRkRqc1diZ2hDV25weVp6QXg0RlkrTUVjeWk5eHFlNDkx
#    CjVxOTNGQkRqbVg0a1lBTCtGT3RXR2RFdGVRM09TbFphWXN5UW45N0RLenVLdndQU1AyV1V3ZTZQ
#    R0VNQzBFSngKTDZPeDdtbGRDZFkwQUxyRjlKNEJ4VWdKNDFNaURJMHpweUFCa2xjPQotLS0tLUVO
#    RCBDRVJUSUZJQ0FURS0tLS0tCg==
#  tls.key: |+
#    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2QUlCQURBTkJna3Foa2lHOXcwQkFRRUZB
#    QVNDQktZd2dnU2lBZ0VBQW9JQkFRQ1ovQmZLcFBaYWt1dk8KTDR4ZjR4NE5ZR2FWSzFzNjRTRVBh
#    TGpIa0lTd0dqcCtqVjByVk5obDhIZGdHdFhVeE9WbDdMREFRb0oyYmVQdQpJaW1hMmxFR3g4WGRO
#    VTJtT2VUcmpSTWZScWpGSHhWZW84R2JDSDRYempKWWdvNzZPTCs4MzVQNGZZdTJURUZICkYyOUtN
#    cURwZ0RQMEhQV3l1NXBrM1F5aHBBUitWL1VSSDJmYlNsV1FKaEIxM01SSXVlbGZmdlc0ZERvUW9J
#    QWEKNE1LMzZkK0VRa1lLcFZ1NmdKSVZHRmY3K01IcDVlbTkzYmhneXhKZVZFSnNlb2FBL3NwU0JE
#    a1NHVVVRem00QgpiRmo2RDNTMVhmRkpNL1pwYlAvczdSdHUzU1p4VVBIZnZwR3RLb3FMTVFrUHgw
#    akpyR3hsYURNc2pYZkdXT3hECkxSL2JoK3VWQWdNQkFBRUNnZ0VBTHhKVEs0MVdDY1lUODRteGZi
#    WnQvMlRTdHhMejVvSGZtMWhGOUN1SGhGWGcKUDhOekVjWDBDT1dEZUl0N2hubFNMdUExLysvVTll
#    TU41RVBwTi84NCtidWtEc1Uyb1hQZE9PeDlSZmhScTBDZgpSYmtGZkNFU2VyQjd6M2JKd2xBS3ZQ
#    QVR5Y2lISndrVWcyajBpbGdEdkoyR1JEOStGRThwR1dCQmRrQXZaM2QrClR1SFNMaGlVZURZdmFD
#    YzVUUHdTM0ZxUCt1TytnUndWVHd0cEVzang2UUdVSlFuZllYY2hFclRHOUY5U2pCNFcKcndXVXF5
#    bFlncGg2R2MvcDg0R2xLYXZZbFZBTTdXZHhjQ2ZLZGtuZyt6UWlYb1BhMjlDdkxmRldOWkJPMUlV
#    YQo5cFB2Nzk3aUYwNHZPNlhQNUI3bTYyNm9IL3FPZnA2SEdqMTlrejdoR1FLQmdRRFJ1WC9tek01
#    Q09QSUI3TDI4CjJLUTMyaUVXMTZncmVucFZzRlhydkFZbkxWVnh3eGFDcjNhWXBDTlJDV09xWWlL
#    R1gzUlhJdTRnSndSVFZwUnUKcFZsbjRkVDBkWjFMeE1aN2RaU2lLeTMrRVFMUUI2VU1FM0R4UGpY
#    RkFlWWZxZ29ZdkFVbWkxRG1HaGpNNGNFSQp1dDkySGU1akRoK21uYlhhYnA0aUIvQWFCd0tCZ1FD
#    NzloSnhwYVJZYjNsRTBEeXVmNVI3UWtuQTJ5MmROT3lvCmVPVmNEZTZtUHdLOTlmU281eTAxd2I1
#    S0VlbERjWkp2NXlMRlkyZk1rbTh1UWZWRzNTaTJDdDJXQlFjdFkyS1AKYXVKd29Qb081T1hIbUd3
#    UWNlWHdMMzB4eXFZTzY1NTJjYllkZCtON2E4MEtjdWxhQmkyTmNTTnYvaGRhYUhCSwoxbEI3aDZJ
#    V2d3S0JnQkkrWmI3cEVBUTR1ZXlxOEhKdUVoTDl1YVVvQzJ3RTBvR0R2bVdzVElpNTY5WGlsNkcw
#    CnE4ZHBkOTBEeVJTNFJyS1R1U1lmVnNHYlEwZ1Fud2JsQVZzRkRTWmEyTjBQZUFpaldOT21sL0Nq
#    QURDaWladjgKVVBYYmFJZ0R1MFlEMzY3NUpDV1BOdkZkVWN6NDBuYjA4cDF1eXg3NHlvNE82QlBo
#    VFlZK1ZJZWZBb0dBVUcrMwo2T2FuOUNpUVR3Q0dWMjdGamhJS0dmd3lBd3E1RkVmWWI1S094SnBH
#    aENDVGVReWxibEhoS3pXTEM0KzR5U2F5CjNLSHpzN29lMWo3bnhsR3lzR1RwK3Q5ZitPNkZLVGJt
#    ZktpSEdvU2VTTkpUdkozaGR1Mzd0Nmt2YzBjbDR5NDYKYjFYMUJjWldVdGhtUUY1UWRDMHNxeXFq
#    dDg3bDcwRFQ1R2xnMWgwQ2dZQnJMc1VOWGRiMVZ2NEZIMGpIdVg1cwpGQUl6bkFhYlRjbHA2d2px
#    OXlXM0E2NFlWRFdmaDRreHNpMDdBZFY2N09yOHRQVkhyeUxDTnp6V3duRm1Geks5ClN2RXdLSm1P
#    RXpUNCtpdmlCa0NaK2NJblFSdEFSaS9uSGNnNTJjWXBKRkZWd2lGUkR0MWs0QmdvRTJIMG10cjYK
#    RVhLT3dKcndmVXZvSG5TM2U5Mno4Zz09Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
