apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - env:
        - name: REGISTRY_HTTP_SECRET
          value: secret
        - name: REGISTRY_HTTP_TLS_CERTIFICATE
          value: /certs/tls.crt
        - name: REGISTRY_HTTP_TLS_KEY
          value: /certs/tls.key
        image: registry:2.7
        name: registry
        ports:
        - containerPort: 5000
        volumeMounts:
          - mountPath: /var/lib/registry
            name: registry-data
          - mountPath: /etc/docker/registry/config.yml
            name: config-volume
            subPath: config.yml
          - mountPath: /certs
            name: tls-certs
      volumes:
        - name: registry-data
          persistentVolumeClaim:
            claimName: registry-pv-claim
        - configMap:
            name: registry-config
          name: config-volume
        - name: tls-certs
          secret:
            secretName: registry-tls
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-tls
type: kubernetes.io/tls
data:
  tls.crt: |+
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzTXpBMU5EUTNNelF3SGhjTk1qUXhNVEF5TVRBMU1qRTBXaGNOTXpReE1ETXhNVEExTWpFMApXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzTXpBMU5EUTNNelF3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFRVkFsQkdEN1RkeHhYVDh6aWR1dFNSekJ1ZW12RjVBcGhpZXdkcU1NQloKSlZkRUpBbW55Z05RRnA4d1VNV1hQMFpNczVucDBMRXRYRkJaMytBb3VkVlpvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVUd0NnJDOTdFR1kzY095WDFMVERUCjhiS1BrTHN3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUlnRDE5Y0lUZ3J5d2pOM1RSbzhULzQvWUluakxCd2MwLzYKRU94c21qT3h5ejBDSVFDakFRVU5NaXV3ZTNTbENueWgvc3NZZFFRRjlrTEhsOE4xSGFKcGpZS212UT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: |+
    MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCZ/BfKpPZakuvO
    L4xf4x4NYGaVK1s64SEPaLjHkISwGjp+jV0rVNhl8HdgGtXUxOVl7LDAQoJ2bePu
    Iima2lEGx8XdNU2mOeTrjRMfRqjFHxVeo8GbCH4XzjJYgo76OL+835P4fYu2TEFH
    F29KMqDpgDP0HPWyu5pk3QyhpAR+V/URH2fbSlWQJhB13MRIuelffvW4dDoQoIAa
    4MK36d+EQkYKpVu6gJIVGFf7+MHp5em93bhgyxJeVEJseoaA/spSBDkSGUUQzm4B
    bFj6D3S1XfFJM/ZpbP/s7Rtu3SZxUPHfvpGtKoqLMQkPx0jJrGxlaDMsjXfGWOxD
    LR/bh+uVAgMBAAECggEALxJTK41WCcYT84mxfbZt/2TStxLz5oHfm1hF9CuHhFXg
    P8NzEcX0COWDeIt7hnlSLuA1/+/U9eMN5EPpN/84+bukDsU2oXPdOOx9RfhRq0Cf
    RbkFfCESerB7z3bJwlAKvPATyciHJwkUg2j0ilgDvJ2GRD9+FE8pGWBBdkAvZ3d+
    TuHSLhiUeDYvaCc5TPwS3FqP+uO+gRwVTwtpEsjx6QGUJQnfYXchErTG9F9SjB4W
    rwWUqylYgph6Gc/p84GlKavYlVAM7WdxcCfKdkng+zQiXoPa29CvLfFWNZBO1IUa
    9pPv797iF04vO6XP5B7m626oH/qOfp6HGj19kz7hGQKBgQDRuX/mzM5COPIB7L28
    2KQ32iEW16grenpVsFXrvAYnLVVxwxaCr3aYpCNRCWOqYiKGX3RXIu4gJwRTVpRu
    pVln4dT0dZ1LxMZ7dZSiKy3+EQLQB6UME3DxPjXFAeYfqgoYvAUmi1DmGhjM4cEI
    ut92He5jDh+mnbXabp4iB/AaBwKBgQC79hJxpaRYb3lE0Dyuf5R7QknA2y2dNOyo
    eOVcDe6mPwK99fSo5y01wb5KEelDcZJv5yLFY2fMkm8uQfVG3Si2Ct2WBQctY2KP
    auJwoPoO5OXHmGwQceXwL30xyqYO6552cbYdd+N7a80KculaBi2NcSNv/hdaaHBK
    1lB7h6IWgwKBgBI+Zb7pEAQ4ueyq8HJuEhL9uaUoC2wE0oGDvmWsTIi569Xil6G0
    q8dpd90DyRS4RrKTuSYfVsGbQ0gQnwblAVsFDSZa2N0PeAijWNOml/CjADCiiZv8
    UPXbaIgDu0YD3675JCWPNvFdUcz40nb08p1uyx74yo4O6BPhTYY+VIefAoGAUG+3
    6Oan9CiQTwCGV27FjhIKGfwyAwq5FEfYb5KOxJpGhCCTeQylblHhKzWLC4+4ySay
    3KHzs7oe1j7nxlGysGTp+t9f+O6FKTbmfKiHGoSeSNJTvJ3hdu37t6kvc0cl4y46
    b1X1BcZWUthmQF5QdC0sqyqjt87l70DT5Glg1h0CgYBrLsUNXdb1Vv4FH0jHuX5s
    FAIznAabTclp6wjq9yW3A64YVDWfh4kxsi07AdV67Or8tPVHryLCNzzWwnFmFzK9
    SvEwKJmOEzT4+iviBkCZ+cInQRtARi/nHcg52cYpJFFVwiFRDt1k4BgoE2H0mtr6
    EXKOwJrwfUvoHnS3e92z8g==
