apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - env:
        - name: REGISTRY_HTTP_SECRET
          value: secret
        - name: REGISTRY_HTTP_TLS_CERTIFICATE
          value: /certs/tls.crt
        - name: REGISTRY_HTTP_TLS_KEY
          value: /certs/tls.key
        image: registry:2.7
        name: registry
        ports:
        - containerPort: 5000
        volumeMounts:
          - mountPath: /var/lib/registry
            name: registry-data
          - mountPath: /etc/docker/registry/config.yml
            name: config-volume
            subPath: config.yml
          - mountPath: /certs
            name: tls-certs
      volumes:
        - name: registry-data
          persistentVolumeClaim:
            claimName: node-db-pv-claim
        - configMap:
            name: registry-config
          name: config-volume
        - name: tls-certs
          secret:
            secretName: registry-tls
