apiVersion: v1
data:
  config.yml: |+
    version: 0.1
    log:
      fields:
        service: registry
    storage:
      delete:
        enabled: true
      cache:
        blobdescriptor: inmemory
      filesystem:
        rootdirectory: /var/lib/registry
    http:
      addr: :5000
      headers:
        X-Content-Type-Options: [nosniff]
        Access-Control-Allow-Origin: ['*']
        Access-Control-Allow-Methods: ['HEAD', 'GET', 'OPTIONS', 'DELETE']
        Access-Control-Allow-Headers: ['Authorization', 'Accept']
        Access-Control-Max-Age: [1728000]
        Access-Control-Allow-Credentials: [true]
        Access-Control-Expose-Headers: ['Docker-Content-Digest']
kind: ConfigMap
metadata:
  name: registry-config
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: registry-tls-cert
#  namespace: default
spec:
  secretName: registry-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: registry.hipr.k8s
  dnsNames:
    - registry.hipr.k8s

