apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: registry-cert
#  namespace: default
spec:
  secretName: registry-tls
  issuerRef:
    name: ca-issuer
    kind: Issuer
  commonName: registry.hipr.k8s.ru
  dnsNames:
    - registry.hipr.k8s.ru
