apiVersion: apps/v1
kind: Deployment
metadata:
  name: dcsreports
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dcsreports
  template:
    metadata:
      labels:
        app: dcsreports
    spec:
      containers:
        - name: dcsreports
          image: johnnydvaroyala/dcsreports:v0.3
          ports:
            - containerPort: 8000
          env:
            - name: INFLUX_DB
              value: dcs_metrics_db
            - name: INFLUX_HOST
              value: influxdb-service
            - name: INFLUXDB_USER
              value: user
            - name: INFLUXDB_USER_PASSWORD
              value: secretpassword
            - name: INFLUX_PORT
              value: "8086"
            - name: REPORT_PATH
              value: /opt
          volumeMounts:
            - mountPath: /opt
              name: dcsreports-data
      volumes:
        - name: dcsreports-data
          persistentVolumeClaim:
            claimName: dcsreports-pv-claim
