apiVersion: apps/v1
kind: Deployment
metadata:
  name: dcsreports
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dcsreports
  template:
    metadata:
      labels:
        app: dcsreports
    spec:
      containers:
        - name: dcsreports
          image: johnnydvaroyala/dcsreports:v0.20
          ports:
            - containerPort: 8000
          env:
#            - name: TZ
#              value: "Europe/Moscow" # Укажите нужный вам часовой пояс
            - name: INFLUX_DB
              value: dcs_metrics_db
            - name: INFLUX_HOST
              value: influxdb-service
            - name: INFLUXDB_USER
              value: user
            - name: INFLUXDB_USER_PASSWORD
              value: secretpassword
            - name: INFLUX_PORT
              value: "8086"
            - name: REPORT_PATH
              value: /opt
            - name: TFNODE
              value: http://dcs-nodes-service:8000
            - name: EX
              value: http://experiment-svc-service:8080
          volumeMounts:
            - mountPath: /opt
              name: dcsreports-data
      volumes:
        - name: dcsreports-data
          persistentVolumeClaim:
            claimName: dcsreports-pv-claim
