apiVersion: v1
kind: Service
metadata:
  name: dcsreports-service
spec:
  selector:
    app: dcsreports
  ports:
    - protocol: TCP
      port: 9890
      targetPort: 8000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "5m"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "5m"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Access-Control-Allow-Origin: $http_origin";
  name: dcsreports-ingress
#  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - host: hipr.k8s
      http:
        paths:
          - path: /api-reports(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: dcsreports-service
                port:
                  number: 9890
