---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dcsreports-pv-volume
  labels:
    type: local
    app: dcsreports
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/hipr/dcsreports-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dcsreports-pv-claim
  labels:
    app: dcsreports
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
