apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
  labels:
    app: grafana
spec:
  capacity:
    storage: 10Gi  # Adjust based on your storage needs
  accessModes:
    - ReadWriteOnce
  storageClassName: manual  # Match the storage class in PVC
  hostPath:
    path: /home/hipr/grafana-data  # Path on the host node
