apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
#  namespace: monitoring  # Adjust if needed
  labels:
    app: grafana
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: grafana  # Match PV label
