#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: prometheus-pvc
##  namespace: monitoring  # Adjust if needed
#  labels:
#    app: prometheus
#spec:
#  storageClassName: standard
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 50Gi
#  selector:
#    matchLabels:
#      app: prometheus  # Match PV label
