apiVersion: apps/v1
kind: Deployment
metadata:
  name: dcs-nodes-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dcs-nodes
  template:
    metadata:
      labels:
        app: dcs-nodes
    spec:
      containers:
        - name: dcs-nodes
          image: johnnydvaroyala/tfnode:v1.0.1
          ports:
            - containerPort: 8000
          env:
            - name: DB_ENGINE
              value: django.db.backends.postgresql
            - name: POSTGRES_DB
              value: tfnode_db
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: DB_HOST
              value: node-db-service
            - name: DB_PORT
              value: '5432'
            - name: KAFKA
              value: kafka-service:9092
