apiVersion: v1
kind: Service
metadata:
  name: dcs-nodes-service
spec:
  selector:
    app: dcs-nodes
  ports:
    - protocol: TCP
      port: 18000
      targetPort: 8000
  type: LoadBalancer
#  type: NodePort
#  ports:
#    - port: 8000
