apiVersion: v1
kind: Service
metadata:
  name: dcs-nodes-service
spec:
  selector:
    app: dcs-nodes
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
#  type: NodePort
#  ports:
#    - port: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Access-Control-Allow-Origin: $http_origin";
  name: dcs-nodes-ingress
#  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - host: hipr.k8s
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: dcs-nodes-service
                port:
                  number: 8000
