apiVersion: v1
kind: Service
metadata:
  name: propagate-srv-service
spec:
  selector:
    app: propagate-srv
  #  type: ClusterIP
  #  ports:
  #    - port: 9050
  #      targetPort: 9050
  ports:
    - name: ws50
      port: 9050
      targetPort: 9050
    - name: ws60
      port: 9060
      targetPort: 9060
  type: LoadBalancer
  externalIPs:
    - 192.168.1.178
