#    - host: dcs
#      http:
#        paths:
#          - path: /(api/.*)
#            backend:
#              serviceName: dcs-nodes-service
#              servicePort: 18000
#          - path: /(propagate/.*)
#            backend:
#              serviceName: propagate-srv-service
#              servicePort: 9050

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: rewrite
#  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - host: dcs
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: dcs-nodes-service
                port:
                  number: 18000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: command-socket
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/server-snippets: |
      location / {
       proxy_set_header Upgrade $http_upgrade;
       proxy_http_version 1.1;
       proxy_set_header X-Forwarded-Host $http_host;
       proxy_set_header X-Forwarded-Proto $scheme;
       proxy_set_header X-Forwarded-For $remote_addr;
       proxy_set_header Host $host;
       proxy_set_header Connection "upgrade";
       proxy_cache_bypass $http_upgrade;
       }
spec:
  rules:
    - host: command-ws.dcs
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: command-queue-srv-service
                port:
                  number: 9075

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ws-control
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_http_version 1.1;
      proxy_set_header Upgrade "websocket";
      proxy_set_header Connection "Upgrade";
    nginx.ingress.kubernetes.io/proxy-read-timeout: '3600'
    nginx.ingress.kubernetes.io/proxy-send-timeout: '3600'
  namespace: dcs
spec:
  rules:
    - host: ws.control
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: command-queue-srv-service
                port:
                  number: 9075
