controller:
  kind: DaemonSet

  reportNodeInternalIp: true


#  hostPort:
#    enabled: true
#    ports:
#      http: 80
#      https: 443

  publishService:
    # -- Enable 'publishService' or not
    enabled: true

  service:
    type: LoadBalancer
    externalIPs:
      - 192.168.127.20

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

  allowSnippetAnnotations: true

  #udp:
    # -- Allows customization of the udp-services-configmap; defaults to $(POD_NAMESPACE)
    #configMapNamespace: "ingress-nginx/udp-services"
