controller:
  kind: DaemonSet

  reportNodeInternalIp: true

  hostPort:
    enabled: true
    ports:
      http: 80
      https: 443

  service:
    type: NodePort
#    externalIPs:
#      - 192.168.1.178

#  metrics:
#    enabled: true
#    serviceMonitor:
#      enabled: true
