controller:
  kind: DaemonSet

  #reportNodeInternalIp: true

  hostPort:
    enabled: true
    ports:
      http: 81
      https: 4443

  service:
    type: LoadBalancer
    externalIPs:
      - 192.168.1.178

#  metrics:
#    enabled: true
#    serviceMonitor:
#      enabled: true
