controller:
  kind: DaemonSet # Runs on every node, ideal for local traffic routing in bare-metal environments.

  reportNodeInternalIp: true # Uses node's internal IP for Ingress Controller communication.

  hostPort:
    enabled: true
    ports:
      http: 80
      https: 443

  publishService:
    enabled: true # Ensures external IP of the service is published.

  service:
    type: LoadBalancer
    externalIPs:
      - 192.168.127.20 # Your desired external IP.

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true # Enables monitoring via Prometheus.

  allowSnippetAnnotations: true # Allows custom NGINX configuration via annotations in Ingress resources.

  udp:
    configMapNamespace: "ingress-nginx" # Use default namespace or customize as necessary.

  extraArgs: # Use this for configurations like proxy body size.
    proxy-body-size: "1000m"

  config:
    # Ensure larger request sizes are supported.
    proxy-body-size: "1000m"

  admissionWebhooks:
    enabled: true # Ensure admission webhook is enabled for validating Ingress.
    timeoutSeconds: 10
