controller:
  kind: DaemonSet

  reportNodeInternalIp: true

  hostPort:
    enabled: true
    ports:
      http: 80
      https: 443

  service:
    type: LoadBalancer
    externalIPs:
      - 192.168.127.20

#  metrics:
#    enabled: true
#    serviceMonitor:
#      enabled: true
