kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: ingress-nginx
data:
  stream-snippets: | 
    upstream device-response-receiver-udp {
        server device-response-receiver-service.default.svc.cluster.local:9031;
    }
    
    server {
        listen 9031 udp;
        listen [::]:9031 udp;
        proxy_pass device-response-receiver-udp;
        proxy_responses 1;
    }
# важно !!!
