kind: Deployment
apiVersion: apps/v1
metadata:
  name: dcs-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dcs-gateway
  template:
    metadata:
      labels:
        app: dcs-gateway
    spec:
      containers:
        - name: dcs-gateway
          image: snaiperlfc/dcs-gateway:0.0.31-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 5000
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 5000
            initialDelaySeconds: 5
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: dcs-gateway
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    app: dcs-gateway
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dcs-gateway-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: dcs
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dcs-gateway
                port:
                  number: 5000
