FROM nginx:stable-alpine
COPY build/ /usr/share/nginx/html
COPY config.conf /etc/nginx/conf.d/default.conf

#docker build -t snaiperlfc/dcs-front-ui:1.0.21 .
#docker push snaiperlfc/dcs-front-ui:1.0.21
