FROM nginx:1.23.3-alpine-slim
COPY build/ /usr/share/nginx/html
#COPY config.conf /etc/nginx/conf.d/default.conf

#docker build -t snaiperlfc/dcs-front-ui:1.0.20 .
#docker push snaiperlfc/dcs-front-ui:1.0.20
