---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv-volume
  labels:
    type: local
    app: grafana
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/cephfs/grafana-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pv-claim
  labels:
    app: grafana
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-config-pv-volume
  labels:
    type: local
    app: grafana
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/cephfs/grafana-config"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-config-pv-claim
  labels:
    app: grafana
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
