apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - containerPort: 3000
          env:
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "true"
            - name: GF_AUTH_ANONYMOUS_ORG_NAME
              value: "HIPR"
            - name: GF_AUTH_ANONYMOUS_ORG_ROLE
              value: "Viewer"
            #            - name: GF_AUTH_BASIC_ENABLED
            #              value: "false"
            #            - name: GF_AUTH_PROXY_ENABLED
            #              value: "false"
            - name: GF_SECURITY_ALLOW_EMBEDDING
              value: "true"

          volumeMounts:
            - mountPath: /var/lib/grafana/
              name: grafana-data
      #            - mountPath: /etc/grafana/grafana.ini
      #              name: grafana-config
      #              subPath: grafana.ini

      securityContext:
        runAsUser: 0
        fsGroup: 0

      volumes:
        - name: grafana-data
          persistentVolumeClaim:
            claimName: grafana-pv-claim
#        - name: grafana-config
#          configMap:
#            name: grafana-ini
