apiVersion: apps/v1
kind: Deployment
metadata:
  name: experiment-svc-deployment
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: experiment-service
  template:
    metadata:
      labels:
        app: experiment-service
    spec:
      containers:
        - name: experiment-service
          image: snaiperlfc/experiment-service:0.0.9-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
#            - name: TZ
#              value: "Europe/Moscow" # Укажите нужный вам часовой пояс
            - name: SPRING_DATA_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: experiment-svc-mongodb-secret
                  key: MONGODB_URI
