apiVersion: v1
kind: PersistentVolume
metadata:
  name: mosquitto-pv
  labels:
    app: mosquitto
spec:
  capacity:
    storage: 1Gi  # Adjust based on your storage needs
  accessModes:
    - ReadWriteOnce
  storageClassName: standard  # Match the storage class in PVC
  hostPath:
    path: /home/hipr/mosquitto  # Path on the host node
