apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-pvc
  labels:
    app: mosquitto
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: mosquitto  # Match PV label
