kind: Deployment
apiVersion: apps/v1
metadata:
  name: dcs-front-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dcs-front-ui
  template:
    metadata:
      labels:
        app: dcs-front-ui
    spec:
      containers:
        - name: dcs-front-ui
          image: snaiperlfc/dcs-front-ui:1.0.22
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: dcs-front-ui
spec:
  ports:
    - protocol: TCP
      port: 18080
      targetPort: 80
  type: LoadBalancer
  #  type: NodePort
  #  ports:
  #    - port: 80
  #      targetPort: 80
  #      protocol: TCP
  #      nodePort: 31000
  selector:
    app: dcs-front-ui
