apiVersion: apps/v1
kind: Deployment
metadata:
  name: visualization-settings-srv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visualization-settings-srv
  template:
    metadata:
      labels:
        app: visualization-settings-srv
    spec:
      containers:
        - name: visualization-settings-srv
          image: skylis/dcs.viz.settings:0.0.6
          ports:
            - containerPort: 5150
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://visualization-settings-db-service:5432/form_settings_db
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
