apiVersion: apps/v1
kind: Deployment
metadata:
  name: experiment-svc-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: experiment-svc-mongodb
  template:
    metadata:
      labels:
        app: experiment-svc-mongodb
    spec:
      containers:
        - name: experiment-svc-mongodb
          image: mongo
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: experiment-svc-mongodb-secret
                  key: MONGODB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: experiment-svc-mongodb-secret
                  key: MONGODB_ROOT_PASSWORD
          volumeMounts:
            - mountPath: /data/db
              name: mongodb-data
            - mountPath: /etc/mongo/mongod.conf
              name: config-volume
              subPath: mongod.conf
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: experiment-svc-mongodb-pvc
        - name: config-volume
          configMap:
            name: experiment-svc-mongodb-config
