apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-experiment-svc-pv-volume
  labels:
    type: local
    app: experiment-service
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/cephfs/mongodb-data-experiment-svc"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-experiment-svc-pv-claim
  labels:
    app: experiment-service
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual
