apiVersion: apps/v1
kind: Deployment
metadata:
  name: experiment-svc-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: experiment-svc-mongodb
  template:
    metadata:
      labels:
        app: experiment-svc-mongodb
    spec:
      containers:
        - name: experiment-svc-mongodb
          image: mongo
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 27017
          env:
          volumeMounts:
            - mountPath: /data/db
              name: mongodb-data
            - mountPath: /etc/mongo/mongod.conf
              name: config-volume
              subPath: mongod.conf
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb-experiment-svc-pv-claim
        - name: config-volume
          configMap:
            name: experiment-svc-mongodb-config
