kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: ingress-nginx
data:
  stream-snippets: | 
    upstream data-server-service-udp {
        server data-server-service.default.svc.cluster.local:9029;
    }
    
    server {
        listen 9029 udp;
        listen [::]:9029 udp;
        proxy_pass data-server-service-udp;
        proxy_responses 1;
    }
# важно !!!
