apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: redis-deployment
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
        - name: redis-insight
          image: redislabs/redisinsight:latest
          ports:
            - containerPort: 8001
