apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-insight-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-insight
  template:
    metadata:
      labels:
        app: redis-insight
    spec:
      containers:
        - name: redis-insight
          image: redislabs/redisinsight:1.13.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8001
