---
apiVersion: v1
kind: Service
metadata:
  name: redis-insight-service
spec:
  selector:
    app: redis-insight
  ports:
    - protocol: TCP
      port: 18001
      targetPort: 8001
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redis-insight-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: redis
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: redis-insight-service
                port:
                  number: 18001
