---
apiVersion: v1
kind: Service
metadata:
  name: redis-insight-service
spec:
  selector:
    app: redis-insight
  ports:
    - name: http
      protocol: TCP
      port: 18001
      targetPort: 8001
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redis-insight-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host: k8s
      http:
        paths:
          - path: /redis
            pathType: Prefix
            backend:
              service:
                name: redis-insight-service
                port:
                  number: 18001
