apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis
  type: NodePort
  ports:
    - port: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-insight-service
spec:
  selector:
    app: redis-insight
  ports:
    - protocol: TCP
      port: 18001
      targetPort: 8001
  type: LoadBalancer
