apiVersion: v1
kind: PersistentVolume
metadata:
  name: nodered-pv
  labels:
    app: node-red
spec:
  capacity:
    storage: 10Gi  # Adjust based on your storage needs
  accessModes:
    - ReadWriteOnce
  storageClassName: standard  # Match the storage class in PVC
  hostPath:
    path: /home/hipr/nodered  # Path on the host node
