apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nodered-pvc
#  namespace: monitoring  # Adjust if needed
  labels:
    app: node-red
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: node-red  # Match PV label
