apiVersion: v1
kind: Service
metadata:
  name: node-red-service
spec:
  selector:
    app: node-red
  ports:
    - protocol: TCP
      port: 1881
      targetPort: 1880
  type: LoadBalancer
  externalIPs:
    - 192.168.127.20
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Access-Control-Allow-Origin: $http_origin";
  name: node-red-ingress
#  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - host: node-red.hipr.k8s
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: node-red-service
                port:
                  number: 1881