---
- name: Install and configure NFS server
  hosts: 192.168.127.20
  become: true

  tasks:
    - name: Install NFS server package
      package:
        name: nfs-utils
        state: present

    - name: Enable and start NFS server service
      service:
        name: nfs-server
        state: started
        enabled: yes

    - name: Add export configuration to /etc/exports
      lineinfile:
        path: /etc/exports
        line: "/mnt/nfs 192.168.127.0/24(rw,sync,no_root_squash)"
        insertafter: EOF

    - name: Apply new configurations
      command: exportfs -a

    - name: Allow NFS traffic in firewall
      firewalld:
        service: nfs
        state: enabled
        immediate: yes
